spring:
  datasource:
    url: jdbc:mysql://192.168.80.129:3306/news_db?useUnicode=true&characterEncoding=UTF-8&useSSL=true
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    
